import { useParams } from "@solidjs/router";
import { useSupabase } from "./supabase";

export function Post() {
  const params = useParams();
  return (
    <div class="bg-gray-800 text-white h-screen">
      <article class="mx-auto max-w-lg pt-12 px-2">
        <header class="text-xl uppercase tracking-wide text-pink-500">
          Post: {params.id}
        </header>
      </article>
    </div>
  );
}

export function NewPost() {
  const supabase = useSupabase();
  const onSubmit = async () => {
    await supabase.from("feed").insert([
      {
        title: "Hello, Solid!",
        description: "Post generated by SolidJS",
      },
    ]);
  };
  return (
    <div class="bg-gray-800 text-white h-screen">
      <form class="mx-auto max-w-lg pt-12 px-2">
        <div class="grid">
          <button
            type="button"
            onclick={onSubmit}
            class="text-xl uppercase tracking-wide bg-pink-500 text-pink-100 rounded py-2 shadow shadow-pink-500/50"
          >
            New post
          </button>
        </div>
      </form>
    </div>
  );
}

export default function Blog() {
  return <div>Blog</div>;
}
